### ISSUE TITLE
Doubts while using the code for my own README

### ISSUE THREAD

**Issue by APratham** [victoriadrake/victoriadrake#1]
**Is your feature request related to a problem? Please describe.**
Yes. I wanted to ask questions but discussions is not enabled

**Describe the solution you'd like**
Enable Discussions for the repository

**Describe alternatives you've considered**
Opening this issue instead

**Additional context**
I tried to use this code for my own README but I am facing issues. It will be great if you can help please. I can share what I am working on (fairly simple to what is there here)

**Comment by victoriadrake** [comment]
I don’t feel it’s necessary to have Discussions on this repo. Please feel free to ask your questions in this issue!

**Comment by APratham** [comment]
Thanks a lot for your response. I already figured out the errors and I'm using the code for my profile README. It was amazing learning a fun new language, Go in the process

**Comment by victoriadrake** [comment]
Great work! Thanks for the update!
